"""GitHub REST API client using only Python stdlib (urllib).

No external HTTP dependency. Uses GITHUB_TOKEN environment variable.
Never auto-merges. Only creates draft PRs.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from typing import Any


GITHUB_API = "https://api.github.com"
_NEVER_AUTOMERGE_NOTE = (
    "⚠️ **This PR was generated by OpenTrace. "
    "Human review is required before merging.** "
    "Do not enable auto-merge."
)


class GitHubClientError(Exception):
    def __init__(self, message: str, status_code: int | None = None) -> None:
        self.status_code = status_code
        super().__init__(message)


class GitHubClient:
    """Minimal GitHub REST API client — draft PR creation only."""

    def __init__(self, token: str) -> None:
        self._token = token

    @classmethod
    def from_env(cls) -> GitHubClient:
        token = os.environ.get("GITHUB_TOKEN", "").strip()
        if not token:
            raise GitHubClientError(
                "GITHUB_TOKEN environment variable is not set. "
                "Set it with: $env:GITHUB_TOKEN='ghp_...'"
            )
        return cls(token)

    # ------------------------------------------------------------------ #
    # Repository resolution
    # ------------------------------------------------------------------ #

    def get_repo(self, owner: str, repo: str) -> dict[str, Any]:
        return self._get(f"/repos/{owner}/{repo}")

    def get_default_branch(self, owner: str, repo: str) -> str:
        data = self.get_repo(owner, repo)
        return str(data.get("default_branch", "main"))

    # ------------------------------------------------------------------ #
    # Branch management
    # ------------------------------------------------------------------ #

    def get_ref(self, owner: str, repo: str, ref: str) -> dict[str, Any]:
        return self._get(f"/repos/{owner}/{repo}/git/refs/heads/{ref}")

    def branch_exists(self, owner: str, repo: str, branch: str) -> bool:
        try:
            self.get_ref(owner, repo, branch)
            return True
        except GitHubClientError as exc:
            if exc.status_code == 404:
                return False
            raise

    # ------------------------------------------------------------------ #
    # Pull request creation
    # ------------------------------------------------------------------ #

    def create_draft_pr(
        self,
        owner: str,
        repo: str,
        *,
        title: str,
        body: str,
        head: str,
        base: str,
    ) -> dict[str, Any]:
        """Create a draft PR. Never auto-merges.

        Returns the PR data dict including 'html_url', 'number', 'node_id'.
        """
        payload: dict[str, Any] = {
            "title": title,
            "body": body,
            "head": head,
            "base": base,
            "draft": True,  # Always draft — never auto-merge
        }
        return self._post(f"/repos/{owner}/{repo}/pulls", payload)

    # ------------------------------------------------------------------ #
    # HTTP helpers
    # ------------------------------------------------------------------ #

    def _get(self, path: str) -> dict[str, Any]:
        req = urllib.request.Request(
            f"{GITHUB_API}{path}",
            headers=self._headers(),
            method="GET",
        )
        return self._execute(req)

    def _post(self, path: str, payload: dict[str, Any]) -> dict[str, Any]:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            f"{GITHUB_API}{path}",
            data=data,
            headers={**self._headers(), "Content-Type": "application/json"},
            method="POST",
        )
        return self._execute(req)

    def _execute(self, req: urllib.request.Request) -> dict[str, Any]:
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = ""
            try:
                body = exc.read().decode("utf-8", errors="replace")
                data = json.loads(body)
                msg = data.get("message", body)
            except Exception:
                msg = body or str(exc)

            hint = ""
            if exc.code == 401:
                hint = " (Troubleshooting: GITHUB_TOKEN is invalid or expired. Generate a new Personal Access Token at github.com/settings/tokens)"
            elif exc.code == 403:
                hint = " (Troubleshooting: Token lacks permission. Ensure token has 'contents: write' and 'pull-requests: write' scopes)"
            elif exc.code == 404:
                hint = " (Troubleshooting: Target repository not found or token lacks access to private repositories)"

            raise GitHubClientError(
                f"GitHub API error {exc.code}: {msg}{hint}", status_code=exc.code
            ) from exc
        except urllib.error.URLError as exc:
            raise GitHubClientError(f"Network error communicating with GitHub: {exc.reason}") from exc

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "OpenTrace-CLI/1.0",
        }
